name: launch-jest-eslint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: make setup
      - run: make lint
      - run: make test
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make test-coverage
          debug: true
